name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-live-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Build demos and typedoc
        run: |
          npm ci
          npm run build:demo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: demo # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.